services:
    crowdfunding-postgres:
        container_name: crowdfunding-postgres
        build: .
        image: crowdfunding-postgres:v1
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=crowdfunding
        volumes:
            - crowdfunding:/bitnami/postgresql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    crowdfunding:  