services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        depends_on:
            - postgres
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - POSTGRES_HOST=postgres
    postgres:
        container_name: postgres
        image: bitnami/postgresql:latest
        ports:
            - "5432:5432"
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - postgres:/bitnami/postgresql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres:  
        driver: local
